### ISSUE TITLE
Wrong breadcrumb for inactive window

### ISSUE THREAD

**Issue by sytranvn** [loctvl842/winbar#2]
Hi, I am using this configuration, but opening different files show same breadcrumb for every files.
```lua
local breadcrumb = function()
	local breadcrumb_status_ok, breadcrumb = pcall(require, "breadcrumb")
	if not breadcrumb_status_ok then
		return
	end
	return breadcrumb.get_breadcrumb()
end

local config = {
	winbar = {
		lualine_a = {},
		lualine_b = {},
		lualine_c = { breadcrumb },
		lualine_x = {},
		lualine_y = {},
		lualine_z = {},
	},
	inactive_winbar = {
		lualine_a = {},
		lualine_b = {},
		lualine_c = { breadcrumb },
		lualine_x = {},
		lualine_y = {},
		lualine_z = {},
	},
}

lualine.setup(config)
```
![Screenshot 2024-03-14 at 09 57 55](https://github.com/loctvl842/breadcrumb.nvim/assets/13009812/b02fb779-cfc2-415e-aa2b-ed9a9916c954)

**Comment by loctvl842** [comment]
Sorry, I forgot to deprecate this repository, please use other better plugins such as barbecue or dropbar. This repository is no longer maintain. I just try to test out SmitshP's plugin.

**Comment by sytranvn** [comment]
Thanks.
